import { reactive } from 'vue'

export const state = reactive({
  currentStyleId: 1,
  customNum: '092',
  customText: 'เทศบาลเมืองอุทัยธานี',
  subTexts: [{ text: '', fontSize: 56, color: '#1F2937' }],
  cabinetColor: '#b0b5b9',
  selectedFont: 'Sarabun',
  scaleLogo: 1.0,
  scaleText: 1.0,
  scaleNum: 1.0,
  currentMaterial: 'matte',
  offsets: { logo: { x: 0, y: 0 }, text: { x: 0, y: 0 }, num: { x: 0, y: 0 } },
  COLORS: { green: '#008542', red: '#DC2626', dark: '#1F2937', white: '#FFFFFF' },
  viewMode: 1,
  showHuman: true,
  showGround: false,
})

export const fonts = [
  { value: 'Sarabun', label: 'Sarabun (ไทย มาตรฐาน)' },
  { value: 'Kanit', label: 'Kanit (ไทย กลม)' },
  { value: 'Prompt', label: 'Prompt (ไทย โมเดิร์น)' },
  { value: 'Noto Sans Thai', label: 'Noto Sans Thai' },
  { value: 'Mitr', label: 'Mitr (ไทย เรียบ)' },
  { value: 'Pridi', label: 'Pridi (ไทย มีหัว ทางการ)' },
  { value: 'Taviraj', label: 'Taviraj (ไทย มีหัว อ่านชัด)' },
  { value: 'Trirong', label: 'Trirong (ไทย มีหัว ป้าย/ประกาศ)' },
  { value: 'Arial', label: 'Arial (Latin)' },
  { value: 'Georgia', label: 'Georgia (Serif)' },
]

export const styles = [
  { id: 1, name: '1. คลาสสิก', desc: 'สมมาตร ตัวเลขเน้น', useCase: 'เหมาะกับป้ายทั่วไป เน้นหมายเลขเด่นชัด' },
  { id: 2, name: '2. อัตลักษณ์', desc: 'สีเขียว สะอาดตา', useCase: 'ใช้กับหน่วยงานที่เน้นสีเขียวเป็นหลัก' },
  { id: 3, name: '3. แนวนอน', desc: 'โลโก้ซ้าย', useCase: 'เหมาะกับข้อความยาว ตู้อยู่ระดับสายตา' },
  { id: 4, name: '4. วงกลม', desc: 'เน้นหมายเลข', useCase: 'มองเห็นหมายเลขจากระยะไกล' },
  { id: 5, name: '5. กรอบมน', desc: 'ตีกรอบหมายเลข', useCase: 'ดูเป็นทางการ เน้นหมายเลขในกรอบ' },
  { id: 6, name: '6. เส้นคั่น', desc: 'แบ่งสัดส่วน', useCase: 'แบ่งเนื้อหาชัดเจน ดูเรียบร้อย' },
  { id: 7, name: '7. เลขยักษ์', desc: 'มองเห็นชัด', useCase: 'ตู้อยู่สูงหรือไกล ต้องการเลขขนาดใหญ่มาก' },
  { id: 8, name: '8. เลขบน', desc: 'หมายเลขนำหน้า', useCase: 'เน้นให้เห็นหมายเลขก่อนข้อมูลอื่น' },
  { id: 9, name: '9. ป้ายทึบ', desc: 'พื้นหลังหมายเลข', useCase: 'เน้นคอนทราสต์สูง เลขบนพื้นทึบ' },
  { id: 10, name: '10. ชิดซ้าย', desc: 'แบบโมเดิร์น', useCase: 'ดีไซน์ร่วมสมัย จัดเรียงชิดซ้าย' },
  { id: 11, name: '11. ชิดขวา', desc: 'แหวกแนว', useCase: 'ดีไซน์แตกต่าง จัดเรียงชิดขวา' },
  { id: 12, name: '12. ข้อความโค้ง', desc: 'ตราประทับ', useCase: 'สร้างความเป็นทางการแบบตราประทับ' },
  { id: 13, name: '13. แนวนอน 2', desc: 'โลโก้กลาง', useCase: 'คล้ายแบบ 1 แต่เน้นโลโก้ตรงกลาง' },
  { id: 14, name: '14. มินิมอล', desc: 'โลโก้+เลข', useCase: 'ใช้ข้อมูลน้อยที่สุด เรียบง่าย' },
  { id: 15, name: '15. ซ้อนทับ', desc: 'Overlap', useCase: 'ดีไซน์เลเยอร์ซ้อนกัน ดูทันสมัย' },
  { id: 16, name: '16. หนาพิเศษ', desc: 'เน้นข้อความ', useCase: 'ตัวอักษรหนา อ่านง่ายจากไกล' },
  { id: 17, name: '17. ขาวกรอบสี', desc: 'ตัดกันชัดเจน', useCase: 'พื้นขาวกรอบเขียว คอนทราสต์สูง' },
  { id: 18, name: '18. โลโก้เล็ก', desc: 'เน้นเลขพิเศษ', useCase: 'ลดขนาดโลโก้ เพิ่มพื้นที่ให้หมายเลข' },
  { id: 19, name: '19. ตาราง', desc: 'กรอบบล็อก', useCase: 'จัดเรียงข้อมูลในกรอบตาราง' },
  { id: 20, name: '20. แผ่นเพลท', desc: 'จำลองแผ่นรอง', useCase: 'จำลองแผ่นป้ายโลหะ ดูเป็นทางการ' },
]
